### ISSUE TITLE
Incorrect types in webpack environment

### ISSUE THREAD

**Issue by asika32764** [asika32764/spectrum-vanilla#1]
![screenshot 2023-06-05 下午1 10 31](https://github.com/asika32764/spectrum-vanilla/assets/1639206/99be6f82-6aff-403b-82bf-1792ccdc7d08)

**Comment by TheSkallywag** [comment]
I am experiencing the same issue

**Comment by asika32764** [comment]
Should be fixed https://github.com/asika32764/spectrum-vanilla/blob/18f3217d94f4ee5bd476e160866973df5a24428f/dist/index.d.ts
