### ISSUE TITLE
Cannot create two elements of type: "color"

### ISSUE THREAD

**Issue by Olakeen** [asika32764/spectrum-vanilla#2]
Hello,

I was looking for a Spectrum version without jQuery and found yours. Thank you !

I have a problem when I declare more than 1 inputs with the color type.

The last statement overwrites the previous ones, so only one input is displayed.
There's no such problem with Text, Component or Flat types.

My config :

```
<script> 
import Spectrum from 'spectrum-vanilla';

Spectrum.getInstance(#first, {
  type: "color",
  showButtons: false,
  allowEmpty: false
});
 

Spectrum.getInstance(#second, {
  type: "color",
  showButtons: false,
  allowEmpty: false
});

</script>

<input  id="first" name="first"  value="#ffffff">
           
<input  id="second" name="second"  value="#ffffff">
```

![color](https://github.com/asika32764/spectrum-vanilla/assets/26546237/4b5711b2-a4a9-4738-a9c1-9b5ade87e568)
![flat](https://github.com/asika32764/spectrum-vanilla/assets/26546237/b203109e-0c11-4703-bfb4-e61a22215a9a)

**Comment by asika32764** [comment]
Please try 1.1.1

**Comment by Olakeen** [comment]
I can confirm that it's now functional. Thank you !
